Creating an Event
---------------------

This section describes on how to create a standard event by taking the example of creating an “Add To Cart” event. Similarly, you can create custom events of your choice as well.


    .. image:: images/EventManagement.png
        :alt: Calculating depth
        :align: center


Click on Standard Button
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    .. image:: images/addEvent.png
        :scale: 50 %
        :alt: Calculating depth
        :align: center


Fill in the Details
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    .. image:: images/FillDetails.png
        :scale: 40 %
        :alt: Calculating depth
        :align: center

Select Filters
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Steps to obtain CSS selector from the webpage an example:

Step1: login into http://etrial.xyz/ and go to ADD TO CART page

    .. image:: images/addToCart_1.png
        :alt: Calculating depth
        :align: center

Step 2: Right click and select inspect, click on elements option

    .. image:: images/addToCart_2.png
        :alt: Calculating depth
        :align: center


Step 3: Copy and paste the CSS selector by holding the cursor on the “ADD to Cart” button

**selecting outer container**

    .. image:: images/addToCart_4.png
        :alt: Calculating depth
        :align: center


**Selecting inner container**

    .. image:: images/addToCart_3.png
        :alt: Calculating depth
        :align: center


**Set the filter**

    .. image:: images/addToCart_5.png
        :alt: Calculating depth
        :align: center


Set Properties 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Click on the symbol [+] to choose the properties of the event you wish to be captured in this case we have selected price, product name, and quantity, click save after filling in the details


    .. image:: images/Properties.png
        :alt: Calculating depth
        :align: center


**Example: Set Price Properties**

selecting outercontainer

    .. image:: images/Price.png
        :alt: Calculating depth
        :align: center


selecting innercontainer

    .. image:: images/Price_2.png
        :alt: Calculating depth
        :align: center


**Example: Set Quantity Properties**

selecting outercontainer

    .. image:: images/Quantity.png
        :alt: Calculating depth
        :align: center

Save 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Click on Save button to save the event**


